version: '3.8'

services:
  trading_bot:
    build: .
    container_name: trading_bot
    volumes:
      - ./config.yaml:/usr/local/bin/config.yaml:ro
    restart: unless-stopped
    environment:
      - RUST_LOG=info 