services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - RUST_LOG=${RUST_LOG:-better_call_put=debug,hyper=info}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    volumes:
      - ./config.yaml:/app/config.yaml
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "better-call-put"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-'2'}
          memory: ${MEMORY_LIMIT:-2G}
        reservations:
          cpus: ${CPU_RESERVATION:-'1'}
          memory: ${MEMORY_RESERVATION:-1G}
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE:-"100m"}
        max-file: ${LOG_MAX_FILES:-"10"}
        tag: "{{.Name}}"
        labels: "production_status"
        env: "RUST_LOG"
    labels:
      - "com.example.description=Better Call Put Trading Bot"
      - "com.example.version=${VERSION:-1.0}"
      - "com.example.maintainer=Denis Stepanov"
      - "com.example.service=trading"
      - "com.example.environment=${ENVIRONMENT:-production}"

networks:
  app-network:
    driver: bridge
    labels:
      - "com.example.network=trading-network"