services:
  app:
    image: rust:1.85.1-slim-bullseye
    restart: always
    command: sh -c "apt-get update && apt-get install -y pkg-config libssl-dev && cargo run --release"
    volumes:
      - ./:/app
    working_dir: /app